### ISSUE TITLE
如何使用模数和指数生成公钥？

### ISSUE THREAD

**Issue by manfengjun** [Kejiasir/SwiftRSACrypto#1]
目前服务器返回指数和模数，需要本地生成公钥进入加密，一直没找到合适的类库

**Comment by Kejiasir** [comment]
哈哈哈，这么高级的需求，你们是做金融产品吧！你看看这个博客有没有帮助：[RSA加密：利用模数和指数生成公钥加密](http://www.cnblogs.com/tml839720759/p/3926006.html)，我是没有做过！或者你参考下 [OC 版本](https://github.com/Kejiasir/YYRSACrypto/blob/master/YYRSACrypto/YYRSACrypto.m)这个文件里面，有两个我自己用 C 实现的生成秘钥对的方法。
