### ISSUE TITLE
你好，请问，加密参数如果很长就会崩溃，有解决方法吗？ 差不多超过128个字符。就崩溃

### ISSUE THREAD

**Issue by Xue765** [Kejiasir/SwiftRSACrypto#2]

**Comment by Kejiasir** [comment]
RSA加密的效率比较低，不建议加密长数据，并且这个工具不支持分段加密，你可以将需要加密的内容先进行AES, DES...等其它方式加密，再使用 RSA 加密加密后的内容，解密反之。
